# Generated by Django 3.0.8 on 2020-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('repo_url', models.TextField(max_length=50)),
                ('build_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('NOT_BUILT', 'Not Built')], default='NOT_BUILT', max_length=10)),
                ('build_date', models.DateTimeField(blank=True)),
                ('build_output', models.TextField(blank=True)),
                ('aur_push', models.BooleanField(default=False)),
            ],
        ),
    ]
