# Generated by Django 3.0.8 on 2020-07-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='build_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='build_output',
            field=models.TextField(null=True),
        ),
    ]
