# Generated by Django 3.0.8 on 2020-07-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_manager', '0002_auto_20200731_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='repo_url',
            field=models.CharField(max_length=100),
        ),
    ]
