# Generated by Django 3.0.8 on 2020-08-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_manager', '0003_auto_20200731_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='build_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='build_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
