# Generated by Django 3.1.3 on 2020-11-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_manager', '0006_auto_20200912_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='aur_push_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
