# Generated by Django 3.2.20 on 2023-08-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_manager', '0007_package_aur_push_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='makepkg_extra_args',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
