# Generated by Django 3.2.20 on 2023-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_manager', '0009_gpgkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='build_status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('NOT_BUILT', 'Not Built'), ('BUILDING', 'Building'), ('PREPARING', 'Preparing'), ('WAITING', 'Waiting')], default='NOT_BUILT', max_length=10),
        ),
    ]
